<?php

return [
    'options' => [
        ['value' => 'USD', 'label' => 'USD — US Dollar'],
        ['value' => 'EUR', 'label' => 'EUR — Euro'],
        ['value' => 'GBP', 'label' => 'GBP — British Pound'],
        ['value' => 'INR', 'label' => 'INR — Indian Rupee'],
        ['value' => 'JPY', 'label' => 'JPY — Japanese Yen'],
        ['value' => 'CNY', 'label' => 'CNY — Chinese Yuan'],
        ['value' => 'AUD', 'label' => 'AUD — Australian Dollar'],
        ['value' => 'CAD', 'label' => 'CAD — Canadian Dollar'],
        ['value' => 'CHF', 'label' => 'CHF — Swiss Franc'],
        ['value' => 'SGD', 'label' => 'SGD — Singapore Dollar'],
        ['value' => 'NZD', 'label' => 'NZD — New Zealand Dollar'],
        ['value' => 'HKD', 'label' => 'HKD — Hong Kong Dollar'],
        ['value' => 'SEK', 'label' => 'SEK — Swedish Krona'],
        ['value' => 'NOK', 'label' => 'NOK — Norwegian Krone'],
        ['value' => 'DKK', 'label' => 'DKK — Danish Krone'],
        ['value' => 'AED', 'label' => 'AED — UAE Dirham'],
        ['value' => 'SAR', 'label' => 'SAR — Saudi Riyal'],
        ['value' => 'QAR', 'label' => 'QAR — Qatari Riyal'],
        ['value' => 'KWD', 'label' => 'KWD — Kuwaiti Dinar'],
        ['value' => 'OMR', 'label' => 'OMR — Omani Rial'],
        ['value' => 'ZAR', 'label' => 'ZAR — South African Rand'],
        ['value' => 'BRL', 'label' => 'BRL — Brazilian Real'],
        ['value' => 'MXN', 'label' => 'MXN — Mexican Peso'],
        ['value' => 'ARS', 'label' => 'ARS — Argentine Peso'],
        ['value' => 'CLP', 'label' => 'CLP — Chilean Peso'],
        ['value' => 'COP', 'label' => 'COP — Colombian Peso'],
        ['value' => 'PEN', 'label' => 'PEN — Peruvian Sol'],
        ['value' => 'TRY', 'label' => 'TRY — Turkish Lira'],
        ['value' => 'THB', 'label' => 'THB — Thai Baht'],
        ['value' => 'MYR', 'label' => 'MYR — Malaysian Ringgit'],
        ['value' => 'IDR', 'label' => 'IDR — Indonesian Rupiah'],
        ['value' => 'KRW', 'label' => 'KRW — South Korean Won'],
        ['value' => 'VND', 'label' => 'VND — Vietnamese Dong'],
        ['value' => 'PHP', 'label' => 'PHP — Philippine Peso'],
        ['value' => 'ILS', 'label' => 'ILS — Israeli New Shekel'],
        ['value' => 'PLN', 'label' => 'PLN — Polish Złoty'],
        ['value' => 'HUF', 'label' => 'HUF — Hungarian Forint'],
        ['value' => 'CZK', 'label' => 'CZK — Czech Koruna'],
        ['value' => 'RUB', 'label' => 'RUB — Russian Ruble'],
        ['value' => 'NGN', 'label' => 'NGN — Nigerian Naira'],
        ['value' => 'GHS', 'label' => 'GHS — Ghanaian Cedi'],
        ['value' => 'EGP', 'label' => 'EGP — Egyptian Pound'],
    ],
];
